export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const NEWSPAPER_EDIT_SUCCESS = 'NEWSPAPER_EDIT_SUCCESS';
export const NEWSPAPER_EDIT_FAIL = 'NEWSPAPER_EDIT_FAIL';
export const STOP_NEWSPAPER_LOADING = 'STOP_NEWSPAPER_LOADING';
export const START_NEWSPAPER_LOADING = 'START_NEWSPAPER_LOADING';
export const NEWSPAPER_CREATED = 'NEWSPAPER_CREATED';
export const SET_NEWSPAPERS = 'SET_NEWSPAPERS';
export const DELETE_NEWSPAPER = 'DELETE_NEWSPAPER';

export const SUBSCRIPTION_EDIT_SUCCESS = 'SUBSCRIPTION_EDIT_SUCCESS';
export const SUBSCRIPTION_EDIT_FAIL = 'SUBSCRIPTION_EDIT_FAIL';
export const STOP_SUBSCRIPTION_LOADING = 'STOP_SUBSCRIPTION_LOADING';
export const START_SUBSCRIPTION_LOADING = 'START_SUBSCRIPTION_LOADING';
export const SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED';
export const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS';
export const DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION';
